// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cymcmjotypmfnyjzbgim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bWNtam90eXBtZm55anpiZ2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjE2OTMsImV4cCI6MjA2MDQzNzY5M30.SGdzy9p5vRoay7vuhMorI1v3LfQz8ECYppqMyFkLuGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);